version: '3'
services: 
    db:
        image: mariadb
        restart: always
        ports:
            - "3308:3306"
        environment: 
            MYSQL_ROOT_PASSWORD : 1234
        volumes:
            - ./sqls:/docker-entrypoint-initdb.d