apiVersion: v1
kind: Service
metadata:
  name: tcp-echo-client
  labels:
    app: tcp-echo-client
spec:
  ports:
  - name: tcp
    port: 8021
  # Port 9002 is omitted intentionally for testing the pass through filter chain.
  selector:
    app: echo-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-client
      version: v1
  template:
    metadata:
      labels:
        app: echo-client
        version: v1
    spec:
      containers:
      - name: echo-client
        image: grd-dev.urad.com.tw/hank/echoclient:1.0.0
        imagePullPolicy: IfNotPresent
        args: [ "tcp-echo-server", "8020", "1000" ]
        ports:
        - containerPort: 8021
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tcp-echo-gateway-client
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 31401
      name: tcp
      protocol: TCP
    hosts:
    - "*"
---