apiVersion: v1
kind: Service
metadata:
  name: simple-login-svc
  labels:
    app: simple-login-svc
spec:
  ports:
  - name: tcp
    port: 8033
  # Port 9002 is omitted intentionally for testing the pass through filter chain.
  selector:
    app: simple-login
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-login
      version: v1
  template:
    metadata:
      labels:
        app: simple-login
        version: v1
    spec:
      containers:
      - name: simple-login
        image: grd-dev.urad.com.tw/hank/simplelogin:1.0.0
        imagePullPolicy: IfNotPresent
        args: [ "8033" ]
        ports:
        - containerPort: 8033
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: simple-login-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: simple-login-vsvc
spec:
  hosts:
  - "*"
  gateways:
  - simple-login-gateway
  http:
  - match:
    - uri: 
      exact: /login
    redirect:
      uri: /
      authority: simple-login-svc.default.svc.cluster.local
    route:
    - destination:
        host: simple-login-svc.default.svc.cluster.local
        port:
          number: 8033